name: flutter_paper_trail
description: Fork from metaflow repository. A flutter plugin for PaperTrail logging service
version: 0.0.8
dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.fradip12.flutterpapertrail
    pluginClass: FlutterPaperTrailPlugin


environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0 <2.10.2"